#ifndef PC_INTERRUPT
#define PC_INTERRUPT

#include <avr/io.h>
#include <avr/interrupt.h>

#define PCIEB PCIE0
#define PCIEC PCIE1
#define PCIED PCIE2

/* Enable one of the pin change interrupts avaiable specified by pciex
 * and select which I/O pin will cause the interrupt by setting the
 * Pin Change Mask Register */
void PCINT_enable(uint8_t pin, uint8_t pciex);

/* Disable the interrupt generated by the given I/O pin and
 * disable the respective pin change interrupt if there is no
 * other I/O pin selectd for it */
void PCINT_disable(uint8_t pin, uint8_t pciex);

/* Disable all pin change interrupts and clear all the I/O pin masks */
void PCINT_disable_all(void);

#endif
