#include "pc_interrupt.h"

/* Enable one of the pin change interrupts avaiable specified by pciex
 * and select which I/O pin will cause the interrupt by setting the
 * Pin Change Mask Register */
void PCINT_enable(uint8_t pin, uint8_t pciex)
{
	PCICR |= _BV(pciex);
	switch (pciex) {
		case 0:
			PCMSK0 |= _BV(pin);
			break;
		case 1:
			PCMSK1 |= _BV(pin);
			break;
		case 2:
			PCMSK2 |= _BV(pin);
			break;
	}
}

/* Disable the interrupt generated by the given I/O pin and
 * disable the respective pin change interrupt if there is no
 * other I/O pin selectd for it */
void PCINT_disable(uint8_t pin, uint8_t pciex)
{
	switch (pciex) {
		case 0:
			PCMSK0 &= ~_BV(pin);
			if(PCMSK0 == 0) PCICR &= ~_BV(pciex);
			break;
		case 1:
			PCMSK1 &= ~_BV(pin);
			if(PCMSK1 == 0) PCICR &= ~_BV(pciex);
			break;
		case 2:
			PCMSK2 &= ~_BV(pin);
			if(PCMSK2 == 0) PCICR &= ~_BV(pciex);
			break;
	}
}

/* Disable all pin change interrupts and clear all the I/O pin masks */
void PCINT_disable_all(void)
{
	PCMSK0 = 0;
	PCMSK1 = 0;
	PCMSK2 = 0;
	PCICR = 0;
}
